project:
  type: website
  output-dir: docs

website:
  title: "Learning Screenwriting - Themes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: screenplays.qmd
        text: Screenplays

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
